name: Upload esmini artifacts
description: Upload esmini artifacts

runs:
  using: 'composite'

  steps:
    - name: Bundle Release artifacts - MacOS
      if: runner.os == 'macOS'
      shell: bash
      run: lipo -create bin/libesminiRMLib.dylib -output bin/esminiRMLib.bundle
        && lipo -create bin/libesminiLib.dylib -output bin/esminiLib.bundle

    - name: Copy Release artifacts to esmini prefix folder structure
      shell: bash
      run: >
        mkdir esmini &&
        tar -c -p
        bin/
        EnvironmentSimulator/Applications/odrplot/xodr.py
        EnvironmentSimulator/Libraries/esminiRMLib/esminiRMLib.hpp
        EnvironmentSimulator/Libraries/esminiRMLib/esminiRMWrapper.cs
        EnvironmentSimulator/Libraries/esminiRMLib/esminiRMUnityUtil.cs
        EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp
        EnvironmentSimulator/Libraries/esminiLib/ESMiniWrapper.cs
        version.txt
        test/sim.csv
        test/sim_py.csv
        | tar -p -C esmini -x

    - name: Make scripts and binaries runnable for Release - Unix
      if: runner.os == 'macOS' || runner.os == 'Linux'
      shell: bash
      run: sudo chmod -R +x ./esmini/bin/

    - name: Archive release binaries
      shell: bash
      run: 7z a esmini-bin_${{ runner.os }}.zip esmini/*

    - name: Upload release artifact
      uses: actions/upload-artifact@v4.3.6
      with:
        name: esmini-bin_${{ runner.os }}
        path: esmini-bin_${{ runner.os }}.zip

    - name: Copy demo artifacts to esmini prefix folder structure
      shell: bash
      run: >
        ./scripts/generate_binary_dist.sh

    - name: Make scripts and binaries runnable for Demo - Unix
      if: runner.os == 'macOS' || runner.os == 'Linux'
      shell: bash
      run: sudo chmod -R +x ./esmini-demo/run/
        && sudo chmod -R +x ./esmini-demo/scripts/
        && sudo chmod -R +x ./esmini-demo/bin/

    - name: Archive demo binaries
      shell: bash
      run: 7z a esmini-demo_${{ runner.os }}.zip esmini-demo/*

    - name: Upload demo artifact
      uses: actions/upload-artifact@v4.3.6
      with:
        name: esmini-demo_${{ runner.os }}
        path: esmini-demo_${{ runner.os }}.zip
