name: "Run osc-validation"
description: "Install osc-validation, run pytest suite, convert JUnit XML to HTML, and collect artifacts"
runs:
  using: "composite"
  steps:

    - name: Checkout osc-validation
      uses: actions/checkout@v4
      with:
        repository: PMSFIT/osc-validation
        ref: 44c6a2f4c8363aebf8fcb8e9822fdcca677d51f6
        fetch-depth: 1
        path: osc-validation

    - name: Set up Python venv
      shell: bash
      run: |
        pushd osc-validation
        python3 -m venv .venv
        source .venv/bin/activate
        pip install -e .
        pip install junit2html
        popd

    - name: Run osc-validation pytest suite
      id: run_tests
      shell: bash
      run: |
        pushd osc-validation
        source .venv/bin/activate

        SIM_BIN="$(pwd)/../bin/esmini"
        echo "Using esmini binary: $SIM_BIN"

        mkdir -p osc_validation_results

        set +e
        pytest validation/scenario/ \
          --tool ESMini \
          --toolpath "$SIM_BIN" \
          -m trajectory \
          --basetemp osc_validation_results \
          --junitxml osc_validation_results/junit.xml
        code=$?
        echo "exitcode=$code" >> $GITHUB_OUTPUT
        echo "osc-validation finished with exit code $code"

        cd osc_validation_results
        junit2html junit.xml junit.html

        popd

    - name: Upload osc-validation artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: osc-validation
        path: osc-validation/osc_validation_results

    - name: Fail if tests failed
      if: always()
      shell: bash
      run: |
        if [ "${{ steps.run_tests.outputs.exitcode }}" != "0" ]; then
          echo "osc-validation failed"
          exit 1
        fi
