# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osi3/osi_version.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16osi3/osi_version.proto\x12\x04osi3\x1a google/protobuf/descriptor.proto\"W\n\x10InterfaceVersion\x12\x15\n\rversion_major\x18\x01 \x01(\r\x12\x15\n\rversion_minor\x18\x02 \x01(\r\x12\x15\n\rversion_patch\x18\x03 \x01(\r:Y\n\x19\x63urrent_interface_version\x12\x1c.google.protobuf.FileOptions\x18\xe8\xf8\x04 \x01(\x0b\x32\x16.osi3.InterfaceVersionB\x14H\x01\xc2\xc6\'\x02\x08\x03\xc2\xc6\'\x02\x10\x05\xc2\xc6\'\x02\x18\x00')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'osi3.osi_version_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
  google_dot_protobuf_dot_descriptor__pb2.FileOptions.RegisterExtension(current_interface_version)

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\302\306\'\002\010\003\302\306\'\002\020\005\302\306\'\002\030\000'
  _INTERFACEVERSION._serialized_start=66
  _INTERFACEVERSION._serialized_end=153
# @@protoc_insertion_point(module_scope)
