# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osi3/osi_groundtruth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from osi3 import osi_version_pb2 as osi3_dot_osi__version__pb2
from osi3 import osi_common_pb2 as osi3_dot_osi__common__pb2
from osi3 import osi_environment_pb2 as osi3_dot_osi__environment__pb2
from osi3 import osi_trafficsign_pb2 as osi3_dot_osi__trafficsign__pb2
from osi3 import osi_trafficlight_pb2 as osi3_dot_osi__trafficlight__pb2
from osi3 import osi_roadmarking_pb2 as osi3_dot_osi__roadmarking__pb2
from osi3 import osi_lane_pb2 as osi3_dot_osi__lane__pb2
from osi3 import osi_logicallane_pb2 as osi3_dot_osi__logicallane__pb2
from osi3 import osi_referenceline_pb2 as osi3_dot_osi__referenceline__pb2
from osi3 import osi_object_pb2 as osi3_dot_osi__object__pb2
from osi3 import osi_occupant_pb2 as osi3_dot_osi__occupant__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aosi3/osi_groundtruth.proto\x12\x04osi3\x1a\x16osi3/osi_version.proto\x1a\x15osi3/osi_common.proto\x1a\x1aosi3/osi_environment.proto\x1a\x1aosi3/osi_trafficsign.proto\x1a\x1bosi3/osi_trafficlight.proto\x1a\x1aosi3/osi_roadmarking.proto\x1a\x13osi3/osi_lane.proto\x1a\x1aosi3/osi_logicallane.proto\x1a\x1cosi3/osi_referenceline.proto\x1a\x15osi3/osi_object.proto\x1a\x17osi3/osi_occupant.proto\"\xf3\x05\n\x0bGroundTruth\x12\'\n\x07version\x18\x01 \x01(\x0b\x32\x16.osi3.InterfaceVersion\x12\"\n\ttimestamp\x18\x02 \x01(\x0b\x32\x0f.osi3.Timestamp\x12)\n\x0fhost_vehicle_id\x18\x03 \x01(\x0b\x32\x10.osi3.Identifier\x12\x31\n\x11stationary_object\x18\x04 \x03(\x0b\x32\x16.osi3.StationaryObject\x12)\n\rmoving_object\x18\x05 \x03(\x0b\x32\x12.osi3.MovingObject\x12\'\n\x0ctraffic_sign\x18\x06 \x03(\x0b\x32\x11.osi3.TrafficSign\x12)\n\rtraffic_light\x18\x07 \x03(\x0b\x32\x12.osi3.TrafficLight\x12\'\n\x0croad_marking\x18\x08 \x03(\x0b\x32\x11.osi3.RoadMarking\x12)\n\rlane_boundary\x18\t \x03(\x0b\x32\x12.osi3.LaneBoundary\x12\x18\n\x04lane\x18\n \x03(\x0b\x32\n.osi3.Lane\x12 \n\x08occupant\x18\x0b \x03(\x0b\x32\x0e.osi3.Occupant\x12?\n\x18\x65nvironmental_conditions\x18\x0c \x01(\x0b\x32\x1d.osi3.EnvironmentalConditions\x12\x14\n\x0c\x63ountry_code\x18\r \x01(\r\x12\x13\n\x0bproj_string\x18\x0e \x01(\t\x12\x15\n\rmap_reference\x18\x0f \x01(\t\x12\x17\n\x0fmodel_reference\x18\x10 \x01(\t\x12+\n\x0ereference_line\x18\x11 \x03(\x0b\x32\x13.osi3.ReferenceLine\x12\x38\n\x15logical_lane_boundary\x18\x12 \x03(\x0b\x32\x19.osi3.LogicalLaneBoundary\x12\'\n\x0clogical_lane\x18\x13 \x03(\x0b\x32\x11.osi3.LogicalLaneB\x02H\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'osi3.osi_groundtruth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _GROUNDTRUTH._serialized_start=324
  _GROUNDTRUTH._serialized_end=1079
# @@protoc_insertion_point(module_scope)
