# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osi3/osi_occupant.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from osi3 import osi_common_pb2 as osi3_dot_osi__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17osi3/osi_occupant.proto\x12\x04osi3\x1a\x15osi3/osi_common.proto\"\x9a\x06\n\x08Occupant\x12\x1c\n\x02id\x18\x01 \x01(\x0b\x32\x10.osi3.Identifier\x12\x35\n\x0e\x63lassification\x18\x02 \x01(\x0b\x32\x1d.osi3.Occupant.Classification\x12\x31\n\x10source_reference\x18\x03 \x03(\x0b\x32\x17.osi3.ExternalReference\x1a\x85\x05\n\x0e\x43lassification\x12\x11\n\tis_driver\x18\x02 \x01(\x08\x12\x30\n\x04seat\x18\x03 \x01(\x0e\x32\".osi3.Occupant.Classification.Seat\x12G\n\x10steering_control\x18\x04 \x01(\x0e\x32-.osi3.Occupant.Classification.SteeringControl\"\xf7\x01\n\x04Seat\x12\x10\n\x0cSEAT_UNKNOWN\x10\x00\x12\x0e\n\nSEAT_OTHER\x10\x01\x12\x13\n\x0fSEAT_FRONT_LEFT\x10\x02\x12\x14\n\x10SEAT_FRONT_RIGHT\x10\x03\x12\x15\n\x11SEAT_FRONT_MIDDLE\x10\x04\x12\x12\n\x0eSEAT_BACK_LEFT\x10\x05\x12\x13\n\x0fSEAT_BACK_RIGHT\x10\x06\x12\x14\n\x10SEAT_BACK_MIDDLE\x10\x07\x12\x17\n\x13SEAT_THIRD_ROW_LEFT\x10\x08\x12\x18\n\x14SEAT_THIRD_ROW_RIGHT\x10\t\x12\x19\n\x15SEAT_THIRD_ROW_MIDDLE\x10\n\"\xea\x01\n\x0fSteeringControl\x12\x1c\n\x18STEERING_CONTROL_UNKNOWN\x10\x00\x12\x1a\n\x16STEERING_CONTROL_OTHER\x10\x01\x12\x1c\n\x18STEERING_CONTROL_NO_HAND\x10\x02\x12\x1d\n\x19STEERING_CONTROL_ONE_HAND\x10\x03\x12\x1f\n\x1bSTEERING_CONTROL_BOTH_HANDS\x10\x04\x12\x1e\n\x1aSTEERING_CONTROL_LEFT_HAND\x10\x05\x12\x1f\n\x1bSTEERING_CONTROL_RIGHT_HAND\x10\x06\x42\x02H\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'osi3.osi_occupant_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _OCCUPANT._serialized_start=57
  _OCCUPANT._serialized_end=851
  _OCCUPANT_CLASSIFICATION._serialized_start=206
  _OCCUPANT_CLASSIFICATION._serialized_end=851
  _OCCUPANT_CLASSIFICATION_SEAT._serialized_start=367
  _OCCUPANT_CLASSIFICATION_SEAT._serialized_end=614
  _OCCUPANT_CLASSIFICATION_STEERINGCONTROL._serialized_start=617
  _OCCUPANT_CLASSIFICATION_STEERINGCONTROL._serialized_end=851
# @@protoc_insertion_point(module_scope)
